# Generated by Django 4.1.6 on 2023-05-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(default=0)),
                ('StudentS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumanagement.students')),
            ],
        ),
        migrations.CreateModel(
            name='medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=30)),
                ('StudentM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumanagement.students')),
            ],
        ),
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board', models.CharField(max_length=20)),
                ('StudentB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stumanagement.students')),
            ],
        ),
    ]
