# Generated by Django 4.1.6 on 2023-05-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stumanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medium',
            old_name='medium',
            new_name='Medium',
        ),
    ]
