# Generated by Django 4.1.6 on 2023-05-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stumanagement', '0002_rename_medium_medium_medium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='standard',
            new_name='Standard',
        ),
    ]
